# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Bump version
      id: version
      shell: bash
      continue-on-error: true
      run: |
          chmod u+x .github/scripts/bumpversion.sh
          .github/scripts/bumpversion.sh
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        tag_name: ${{ steps.version.outputs.TAG_NAME }}
    - name: NPM install
      run: npm i --force
    - name: Verify imports
      shell: bash
      continue-on-error: true
      run: |
          chmod u+x .github/scripts/verifyimports.sh
          .github/scripts/verifyimports.sh
    - name: Verify licenses   
      shell: bash
      run: |
          chmod u+x .github/scripts/verifylicenses.sh
          .github/scripts/verifylicenses.sh
    - name: Build using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build --if-present
